<?php
$builderHelper = $this->helper('\Cytracon\Builder\Helper\Data');
$rowInnerWidth = $builderHelper->getConfig('general/row_inner_width');
$customCss     = $builderHelper->getConfig('customization/css');

if (!function_exists('minifyCss')) {
    function minifyCss($css) {
        $css = preg_replace('!/\*.*?\*/!s', '', $css);
        $css = preg_replace('/\n\s*\n/', "\n", $css);
        $css = preg_replace('/[\n\r \t]/', ' ', $css);
        $css = preg_replace('/ +/', ' ', $css);
        $css = preg_replace('/ ?([,:;{}]) ?/', '$1', $css);
        return trim($css);
    }
}
?>
<?php if ($rowInnerWidth || $customCss) { ?>
<style>
    <?php if ($rowInnerWidth): ?>
    @media (min-width: <?= (int)$rowInnerWidth ?>px) {
        .cytracon-builder .mgz-container {width: <?= $rowInnerWidth ?>;}
    }
    <?php endif; ?>
    <?= minifyCss($customCss) ?>
</style>
<?php } ?>
